### ISSUE TITLE
connected but no internet

### ISSUE THREAD

**Issue by malikshi** [iw4p/OpenConnect-VPN-Server#1]
vps vultr

**Comment by iw4p** [comment]
Hello, This script tested on Ubuntu 16.04 and 18.04, May I know your OS details?

**Comment by malikshi** [comment]
Ubuntu 18.04. I got private IPs 192.168.1.1 from anyconnect ?? Which setting to change this? I got error bcs my router also 192.168.1.1

**Comment by iw4p** [comment]
This script should run on the server, I think you're trying to run it on your system, If not, just try to run the `install()` commands on the .sh file manually on terminal, and change all `ip` to what you want.

**Comment by malikshi** [comment]
>> This script should run on the server

yah im running this script on server. then im trying in android client to connect OpenConnect server that im installed to, but the android client cant connect to the internet. did you added `net.ipv4.ip_forward = 1` active?

**Comment by iw4p** [comment]
No, If you need it you can use this command to enable IP Forwarding
`echo 1 > /proc/sys/net/ipv4/ip_forward`
