### ISSUE TITLE
Openconnect Android client is not working 

### ISSUE THREAD

**Issue by ber-serker** [iw4p/OpenConnect-VPN-Server#10]
I ran the script on my ubuntu server and it's working. I can connect via windows client openconnect app. But the android client is not working. 

11:48:08 LIB: SSL connection failure: The operation timed out
11:48:08 LIB: Failed to open HTTPS connection to vpn.******.org
11:48:08 VPN terminated with errors
11:49:28 STAT: attempt=1; first=10/1/22 11:47 AM; prev=10/1/22 11:47 AM
11:49:28 STAT: connect=0; first=NEVER; prev=NEVER
11:49:28 STAT: cancel=1; first=10/1/22 11:48 AM; prev=10/1/22 11:48 AM
11:49:28 LIB: POST https://vpn.*********
11:49:32 LIB: Attempting to connect to server *************:443
11:49:32 LIB: Connected to ***********:443
11:49:32 LIB: SSL negotiation with vpn.********.org
11:50:12 LIB: SSL connection failure: The operation timed out
11:50:12 LIB: Failed to open HTTPS connection to vpn.**********.org
11:50:12 Error obtaining cookie
11:50:16 VPN terminated with errors

**Comment by iw4p** [comment]
Hello,
I'm sorry to hear about that, but I can't help.
Maybe it's better to try other versions of Cisco AnyConnect, or look for another alternatives, which can support this protocol.

**Comment by ber-serker** [comment]
I tried AnyConnect too but it's not working either. Anyway, thank you for the excellent script and immediate response.

**Comment by iw4p** [comment]
You're welcome!
