### ISSUE TITLE
Q: Can we set how much device can connect to server with same account at same time?

### ISSUE THREAD

**Issue by sMohammad14** [iw4p/OpenConnect-VPN-Server#12]
Hi
can we limit server to 1 username / password that only used by one device at same time?
another question, iPhone devices can connect to server with AnyConnect App downloaded from Apple AppStore?

**Comment by iw4p** [comment]
Hi
Yes, inside ocserv.conf you can set your limitation. The default for our script is 2.
And answer for the second question is yes, you need AnyConnect application.

**Comment by sMohammad14** [comment]
thanks for your replay.
can you say me how to open that file?
i am noob in linux and docker.
i can only edit file with nano :D
and after edit file, we must do restart docker? how?
thanks

**Comment by iw4p** [comment]
You can clone the project, modify ocserv.conf, search for building docker file and run docker file, do 'docker build' and it will build it the way you need it. And you have to try docker run command with specific parameters, You can read them on README.MD file.
