### ISSUE TITLE
Send BYE packet: Server request

### ISSUE THREAD

**Issue by Sahandi81** [iw4p/OpenConnect-VPN-Server#17]
Hi.
I watch [youtube toturial](https://www.youtube.com/watch?v=kKsEE-LHO-Y) and config the server step by step.

when I want to connect to the server with `openconnect -b [SERVER IP ADDRESS]`
i get this :
```
SSL negotiation with [SERVER IP ADDRESS]
Server certificate verify failed: signer not found

Certificate from VPN server "[SERVER IP ADDRESS]" failed verification.
Reason: signer not found
```
then ask me if I want to continue or NOT,
after accepting that I enter my username and password and then connected successfully.

everything is ok and I have internet access well. But after a few minutes openconnect failed with :
```
received server disconnect
Send BYE packet: Server request
Session terminated by server; exiting.
```
i tried with anyConnect Cisco(ubuntu)/openconnect(ubuntu)/openconnect(android) and give same error.
How can I fix it?

this is the ubuntu 22.04 openconnect client version :
```
OpenConnect version v8.20-1
Using GnuTLS 3.7.3. Features present: TPMv2, PKCS#11, RSA software token, HOTP software token, TOTP software token, Yubikey OATH, System keys, DTLS, ESP
Supported protocols: anyconnect (default), nc, gp, pulse, f5, fortinet, array
Default vpnc-script (override with --script): /usr/share/vpnc-scripts/vpnc-script

```

**Comment by iw4p** [comment]
Hi Sahand. 
I don't know it happened from server provider or not but may I know how you configured it? By docker or shell script? 
Can you test these solutions? 
https://gitlab.com/openconnect/openconnect/-/issues/327

**Comment by Sahandi81** [comment]
Thanks.
ocserv configuration by docker.

yes, I test it a few hours ago and I don't get my answer!!

**Comment by iw4p** [comment]
Unfortunately I'm not able to test it rn; and before the protests, it's fine. Try to change your server provider or change ocserv.conf parameters.

**Comment by smarteist** [comment]
> Unfortunately I'm not able to test it rn; and before the protests, it's fine. Try to change your server provider or change ocserv.conf parameters.

Set ```auth-timeout = 86400``` in ocserv.conf

**Comment by iw4p** [comment]
> > Unfortunately I'm not able to test it rn; and before the protests, it's fine. Try to change your server provider or change ocserv.conf parameters.
> 
> Set `auth-timeout = 86400` in ocserv.conf

By doing this, the problem will fix? You make sure of it?

**Comment by smarteist** [comment]
> > > Unfortunately I'm not able to test it rn; and before the protests, it's fine. Try to change your server provider or change ocserv.conf parameters.
> > 
> > 
> > Set `auth-timeout = 86400` in ocserv.conf
> 
> By doing this, the problem will fix? You make sure of it?

Yes!
