### ISSUE TITLE
Session terminated by server; exiting

### ISSUE THREAD

**Issue by sinashan** [iw4p/OpenConnect-VPN-Server#18]
Hi,

Thank you for this great and easy-to-setup guide. I successfully created an openconnect connection using your guide and everything seems to be fine. However, my connection gets terminated by the server after roughly about 4 minutes. I tried tampering with dpd and keepalive variables as I thought something had to do with them but nothing changed. Every time I get this message at the end of the connection.

```
Received server disconnect
Send BYE packet: Server request
Session terminated by server; exiting.
```

Any ideas on how this can be fixed? 

Thx

**Comment by iw4p** [comment]
Hello,
Thank you.
I think the server provider restricted your server. Some people also opened an issue, and they are looking for a solution.
You can check other issues. And try other ways. Try to transfer your traffic trough ws.

**Comment by sinashan** [comment]
Oh I just saw that issue 🤦🏻‍♂️ I'm gonna ask the server provider because whatever is happening seems to be on the server side.

**Comment by iw4p** [comment]
Also try both ways to configure ocserv, docker and bash script.
