### ISSUE TITLE
VPN is connected but still can't open any site

### ISSUE THREAD

**Issue by hoootan** [iw4p/OpenConnect-VPN-Server#2]
Hi
My Installation process finished successfully and Although I can connect through AnyConnect GUI, but still can't open any site, where did I mistake?

**Comment by taherfattahi** [comment]
please check your /etc/ocserv/ocserv.conf config file
or see this web site:
[setup openconnect VPN server for cisco anyconnect on ubuntu 14.04](https://www.vultr.com/docs/setup-openconnect-vpn-server-for-cisco-anyconnect-on-ubuntu-14-04-x64)

**Comment by AllaberdiCom** [comment]
There is a typo on line 63:
`sed -i -e 's@#net.ipv4.ip_forward@net.ipv4.ip_forward=1@g' /etc/ocserv/ocserv.conf`

it has to be:

`sed -i -e 's@#net.ipv4.ip_forward@net.ipv4.ip_forward=1@g' /etc/sysctl.conf`

This is the reason why you don't have the internet access through the VPN
