### ISSUE TITLE
Port number and backup users (docker)

### ISSUE THREAD

**Issue by padfo0ot** [iw4p/OpenConnect-VPN-Server#23]
Hi, thank you for this amazing work. 
I have 2 questions (docker version):

1. How can we change the port number after creating the container. 
Let's say we have configured like `443:443`
and now we want to change it to `1234:443`
Is there an option to do it without deleting and recreating the container?

2. How can we backup and restore the user/password file?
It should be under `/etc/ocserv` but how can we access it?
If we want to rebuild the image with our own `ocserv.conf` file, we need to backup this file before that. 

Thank you again.

**Comment by iw4p** [comment]
Hello,
You can find users data on /etc/ocserv/ocpasswd path, it's on the container so you can exec to your container to get what you need. And about your first question, you can run your container on your desired port. The connection between docker and your os can be on the port 443 as default, and have to change the PORT:PORT on your docker command to have this service on another port.
