### ISSUE TITLE
Possibility to edit config file to resolve connection termination problem

### ISSUE THREAD

**Issue by saeedgitt** [iw4p/OpenConnect-VPN-Server#24]
I configured open connect server on docker on an Ubuntu 22.04 . every time the connection is terminated after a while. as I see the config file there has been put in this repo  is a parameter named "auth_timeout". how can I edit that parameter value?

**Comment by iw4p** [comment]
Git clone the project
Modify ocserv.conf file
Create image and run Dockerfile manually

**Comment by saeedgitt** [comment]
Thanks, What about connection termination? any idea? I searched other issues in this repo but didn't find any answer .don't you have any suggestion?

**Comment by iw4p** [comment]
Try to comment or remove UDP port line from ocserv.conf. One TCP line for port 443 is enough.

**Comment by saeedgitt** [comment]
Thanks but it didn't resolve the problem .Here is the Error: 
"
Received server disconnect
Send BYE packet: Server request
Error: argument "via" is wrong: use nexthop syntax to specify multiple via

Session terminated by server; exiting.
"

**Comment by iw4p** [comment]
I suggest modifying ocserv.conf and try it on different VPSs.
