### ISSUE TITLE
After rebooting server vpn is connecting but the download speed is showing zero and can not open anything is there any solution solve this problem

### ISSUE THREAD

**Issue by YRS200** [iw4p/OpenConnect-VPN-Server#25]
After rebooting server vpn is connecting but the download speed is showing zero and can not open anything is there any solution solve this problem?

**Comment by iw4p** [comment]
Reinstall it again.

**Comment by YRS200** [comment]
if i reinstall it i need to add all of users again how i can backup data of users from the server to other server?

**Comment by iw4p** [comment]
You have to back up ocpasswd file inside `/etc/ocserv/ocpasswd`.

**Comment by YRS200** [comment]
can you explain it how to backup it? if possible

**Comment by iw4p** [comment]
Use `cp` or `mv` command to have that file with other name like `passwd.bak` or `passwd2`, then whenever you want you can replace that file with changing its name.

**Comment by YRS200** [comment]
can you explain it clearly sterp by step plz! i am not good at bash scripting thanks!

**Comment by iw4p** [comment]
- `cp /etc/ocserv/ocpasswd ~/ocpasswd`
- Reinstall
- `rm -rf /etc/ocserv/ocpasswd`
- `cp ~/ocpasswd /etc/ocserv/ocpasswd`

**Comment by YRS200** [comment]
![image](https://user-images.githubusercontent.com/110148911/203492466-46f05f32-d984-451d-95e6-366f33383fad.png)

when i want to backup users it is saying this

**Comment by iw4p** [comment]
Can I see the result of `cp /etc/ocserv/ocpasswd ~/ocpasswd`?
And also you can make sure files copied successfully by using `ls ~/` command. If you can see ocpasswd file, It means you backup file successfully.
