### ISSUE TITLE
Not active 

### ISSUE THREAD

**Issue by IR0DayToday** [iw4p/OpenConnect-VPN-Server#26]
# systemctl status ocserv.service
× ocserv.service - OpenConnect SSL VPN server
     Loaded: loaded (/etc/systemd/system/ocserv.service; enabled; vendo>     Active: failed (Result: exit-code) since Mon 2022-11-21 09:48:25 U>       Docs: man:ocserv(8)
    Process: 512191 ExecStart=/usr/local/sbin/ocserv --foreground --pid>   Main PID: 512191 (code=exited, status=1/FAILURE)
        CPU: 11ms

Nov 21 09:48:25 Danial systemd[1]: Started OpenConnect SSL VPN server.
Nov 21 09:48:25 Danial ocserv[512191]: This application is part of ocse>Nov 21 09:48:25 Danial systemd[1]: ocserv.service: Main process exited,>Nov 21 09:48:25 Danial systemd[1]: ocserv.service: Failed with result '>lines 1-12/12 (END)

**Comment by IR0DayToday** [comment]
How to fix it

**Comment by iw4p** [comment]
Check [this](https://gitlab.com/openconnect/ocserv/-/issues/255) out
