### ISSUE TITLE
IOS Client ( anyconnect )

### ISSUE THREAD

**Issue by IR0DayToday** [iw4p/OpenConnect-VPN-Server#28]
Hi,
1- i cannot connect to the ocserv ( run with docker ) with anyconnect client

2- when i try connect to the osserv in android with openconnect client more than once i can't connect.

how to config ocserv.conf ?
how can i fix this ?

thank's

**Comment by iw4p** [comment]
Hello,

You can find it [here](https://github.com/iw4p/OpenConnect-Cisco-AnyConnect-VPN-Server-OneKey-ocserv/issues/22#issuecomment-1304813979).

**Comment by IR0DayToday** [comment]
> Hello,
> 
> You can find it [here](https://github.com/iw4p/OpenConnect-Cisco-AnyConnect-VPN-Server-OneKey-ocserv/issues/22#issuecomment-1304813979).

Hi, actualy i fixed the issue 2 but issue 1 still not fixed...
please help about issue 1

**Comment by iw4p** [comment]
Mostly everyone has problems with AnyConnect Cisco client on iOS platform, some people fix it with implementing a domain. It's based on different parameters so I can not certainly say what can fix your problem.

**Comment by IR0DayToday** [comment]
i try with domain and test it, but something needs to change in ocserv.conf to connect domain ?

**Comment by primemb** [comment]
try Add this to your ocserv.conf:
`tls-priorities = "NORMAL:%SERVER_PRECEDENCE:%COMPAT:-RSA:-VERS-SSL3.0:-ARCFOUR-128"`

**Comment by IR0DayToday** [comment]
> try Add this to your ocserv.conf:
> `tls-priorities = "NORMAL:%SERVER_PRECEDENCE:%COMPAT:-RSA:-VERS-SSL3.0:-ARCFOUR-128"

it's help to fix connection in ios ( anyclient ) ?

**Comment by primemb** [comment]
it should More info [here](https://ocserv.gitlab.io/www/manual.html)

**Comment by DG9Jww** [comment]
> try Add this to your ocserv.conf: `tls-priorities = "NORMAL:%SERVER_PRECEDENCE:%COMPAT:-RSA:-VERS-SSL3.0:-ARCFOUR-128"`

It works! But I don't why when I use AnyConnect on my iphone connected to my ocserv. The speed is extremly slow.
