### ISSUE TITLE
Cant connect to ftp

### ISSUE THREAD

**Issue by ImanIranNejad** [iw4p/OpenConnect-VPN-Server#29]
Hi for docker build it stuck at connecting to ftp is it only for me? Is there something i can do?

**Comment by iw4p** [comment]
Hi

Can you share a screenshot of your commands and its results?

**Comment by ImanIranNejad** [comment]
![Screenshot_2022-12-04-22-45-53-445-edit_com arpaplus adminhands](https://user-images.githubusercontent.com/119811160/205510714-254d7d08-405b-45a6-8358-45ccbb333388.jpg)
![Screenshot_2022-12-04-22-46-17-207-edit_com arpaplus adminhands](https://user-images.githubusercontent.com/119811160/205510716-af6ff9cc-de7c-481a-bcc9-72f37767534a.jpg)

**Comment by iw4p** [comment]
Try `wget ftp://ftp.infradead.org/pub/ocserv/ocserv-1.1.2.tar.xz` on your Terminal and see what happens. URL looks good.

**Comment by ImanIranNejad** [comment]
Ahhh i found the problem.it was closed outbound ports on my vps . Thanks for answering. i will try your script tomorrow

**Comment by iw4p** [comment]
You're welcome.
