### ISSUE TITLE
cant access to server Internet

### ISSUE THREAD

**Issue by mahansalimi** [iw4p/OpenConnect-VPN-Server#3]
after install on ubonto 16.04, i can connect suscessfuly by android openconnect app to server ,but cant access to internet
rx data is 0 byte
how i can solve this problem?

**Comment by iw4p** [comment]
Please check this out: [VPN is connected but still can't open any site](https://github.com/iw4p/OpenConnect-VPN-Server/issues/2)
Also, check the Ocserv port is open and accessible on your VPS.

**Comment by mahansalimi** [comment]
i could solve problem with this line:

1:
sudo iptables -t nat -A POSTROUTING -j MASQUERADE

2:and save rule by this line
sudo apt-get install iptables-persistent
