### ISSUE TITLE
can`t connect in some ISP

### ISSUE THREAD

**Issue by mahdiasd** [iw4p/OpenConnect-VPN-Server#31]
Hello good time
Thank you for your strong and good source code
I have a problem. I installed it on my Ubuntu server through Docker, but it connects to some ISPs and not to others
Is there a way I can connect to more ISP (internet service provider) ?

**Comment by iw4p** [comment]
It's based on ovserv.conf configurations and ISPs. Mostly based on ISPs, so you cannot do so much more than this.

**Comment by mohamad6663661** [comment]
سلام وقت بخیر من مشکل نصب دارم اگر امکانش هست جهت کمک با من در ارتباط باشید با تشکر 
@vpn4030 تلگرام 
mohamadtoloyi@gmail.com
