### ISSUE TITLE
DNS malfunction etc

### ISSUE THREAD

**Issue by shahnazari** [iw4p/OpenConnect-VPN-Server#37]
I used to implement your script with no fault. Recently however it looks like there is a couple of bugs showing up. Server DNS e.g. is disrupted after the install and I need to reconfigure it. On which Linux releases have you tried it?

**Comment by iw4p** [comment]
Hi, installing with docker and its image does not need any specific Linux release or version. Did you use bash script?

**Comment by shahnazari** [comment]
Yes the docker file was incompatible with my Radius so I'm using the script. I fixed it however with manually changing the DNS resolver afterwards.

**Comment by iw4p** [comment]
Great!
Feel free to open a new issue if you have a problem.
