### ISSUE TITLE
automatically block Iran IP

### ISSUE THREAD

**Issue by imanYazizi** [iw4p/OpenConnect-VPN-Server#39]
hi again:)
if you could add a way that ocserv blocks IR ips it would be much harder for them to block and detect it

**Comment by iw4p** [comment]
Hi again,
You mean something like when you are using Ocserv on your mobile phone and you open an Iranian website like bmi . Ir, you want to prevent from it?

**Comment by imanYazizi** [comment]
Yes exactly
Cuz the ISPs can detect that you use foreign Ip and block it

**Comment by iw4p** [comment]
I don't believe that ocserv has a functionality for doing this. Hence, I suggest you to read about **iptables** and block your desired IPs using that. Or [this](https://askubuntu.com/questions/1319825/how-can-i-block-outgoing-traffic-to-a-domain-with-all-subdomains-with-ufw-or-ipt)

**Comment by imanYazizi** [comment]
Yup i got it
I will uee ufw and iptables for that matter
Tnx:)

**Comment by iw4p** [comment]
You're welcome!
