### ISSUE TITLE
request

### ISSUE THREAD

**Issue by ghost** [iw4p/OpenConnect-VPN-Server#41]
Install version 1.1.7 of ocserv and support Ubuntu 22.04.

**Comment by iw4p** [comment]
Hi, use docker. You can specify version in dockerfile by changing ENV OCSERV_VERSION 1.1.2

**Comment by ghost** [comment]
> Hi, use docker. You can specify version in dockerfile by changing ENV OCSERV_VERSION 1.1.2

Hi, is it possible to add ipv6 support?

**Comment by iw4p** [comment]
I can't test it currently, as I don't have access to a server with IPV6.

**Comment by ghost** [comment]
Ok thank you.
