### ISSUE TITLE
Problem with Pam auth

### ISSUE THREAD

**Issue by khanhhung1113** [iw4p/OpenConnect-VPN-Server#44]
I always get this and i cant connect to vpn 
ocserv[814753]: PAM-auth pam_auth_pass: Authentication failure
![image](https://github.com/iw4p/OpenConnect-Cisco-AnyConnect-VPN-Server-OneKey-ocserv/assets/126187146/e8a83f11-5f3a-4e6a-8577-08a5386c5f97)

**Comment by iw4p** [comment]
When you get this error and what command you used?

**Comment by khanhhung1113** [comment]
I got this in ocserv everytime i trying to connect to the server, using cisco anyconnect client

**Comment by iw4p** [comment]
Check [this](https://unix.stackexchange.com/questions/422411/pam-authentication-failure-with-valid-password) out

**Comment by khanhhung1113** [comment]
ty sir
