### ISSUE TITLE
connecting with client

### ISSUE THREAD

**Issue by zhpinkman** [iw4p/OpenConnect-VPN-Server#5]
ocserv[18851]: error in plain authentication; cannot open: /etc/ocserv/ocpasswd

upon connecting with a client this message is shown.

**Comment by iw4p** [comment]
Please take a look at [this issue](https://gitlab.com/openconnect/ocserv/-/issues/108)

**Comment by zhpinkman** [comment]
Thanks

**Comment by Atajan2000** [comment]
Hi there can you add some functions to this script plz!
Change ip address of server
transferring the database to another server
Can you also add this functions and update it

**Comment by Atajan2000** [comment]
after creating client server it is not working what to do

**Comment by tkmw1985** [comment]
For changing ip address u just need use domain, insteed of real ip address, no need migrate or transfer data to another instance simply add users as usually same from previous !

**Comment by guga191280** [comment]
hello, your script is very useful for me, thank you. I have a request. please help me tell me how to make this vpn work only udp 443 connections. help please
